### PR TITLE
Issue 507

### PR DESCRIPTION
**Pull request by lyriccoder**
Please specify the following in the description:

1. #507 
2. Now we use `--exclude_glob` and `--exclude_folder` instead of `--exclude`
@yegor256, since @g4s8  is using *ONLY* `--folder` parameter, we can't set `--folder` to ignore folder.
I created 2 params:
--exclude_folder folder
--exclude_glob **/*test*.java **/package-info.java

@yegor256, Is it ok for u?

### CODE REVIEW

**Comment by acheshkov** [comment]
@lyriccoder Is it kind of breaking changes?

**Comment by lyriccoder** [comment]
@yegor256 did u like the interface?

**Comment by yegor256** [comment]
@lyriccoder I don't understand the difference between `exclude_glob` and `exclude_folder`? if I want to exclude a folder, I would just do `--exclude=src/test/**/*`

**Comment by lyriccoder** [comment]
@yegor256 

exclude_folder is the folder to search "exceptions"
exclude_glob is the list of glob patterns to ignore

**Comment by yegor256** [comment]
@lyriccoder this looks weird. I would use `--exclude` to exclude files and some OTHER name for other purposes. Not "exclude".

**Comment by lyriccoder** [comment]
@yegor256 could you please suggest those 2 names? Because the only person who didn't like the names were you. This feature was reimplemented 2nd time. Could you please suggest 2 names for glob patterns and for folder to exclude?

**Comment by yegor256** [comment]
@lyriccoder `--exclude=src/test/**/*` to exclude these files from analysis (may be used multiple times. The meaning of the second option I don't understand. What is "the folder to search 'exceptions'"?

**Comment by lyriccoder** [comment]
@yegor256,  fixed. Now we have only `--exclude` option.

**Comment by yegor256** [comment]
@lyriccoder great!

**Comment by lyriccoder** [comment]
@acheshkov could you please accept and merge?

**Review by acheshkov — APPROVED** [review]

**Comment by acheshkov** [comment]
@lyriccoder looks like we need Yegor's approve

**Comment by acheshkov** [comment]
@lyriccoder I think the merge is blocked because we have unresolved changes request from @aravij

**Review by aravij — APPROVED** [review]

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
