### PR TITLE
New release

### PR DESCRIPTION
**Pull request by lyriccoder**
@rultor release, tag=1.2.4rc1

### CODE REVIEW

**Comment by lyriccoder** [comment]
@rultor release, tag=1.2.4rc1

**Comment by acheshkov** [comment]
Do 1.2.3

**Comment by lyriccoder** [comment]
@rultor release, tag=`1.2.3rc2`

**Comment by lyriccoder** [comment]
@rultor release, tag=1.2.3rc2

**Comment by lyriccoder** [comment]
@rultor release, tag=`1.2.3rc2`

**Comment by acheshkov** [comment]
@rultor release, tag=`1.2.3rc2`

**Comment by lyriccoder** [comment]
how to merge it @acheshkov?

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
