### PR TITLE
Fix docs in aibolit

### LINKED ISSUE #608: --suppress and --exclude options are not documented
This is what I see:

```
$ aibolit check --help
Version 1.2.6rc1 is available, but you are using 1.2.5
usage: aibolit check < --folder | --filenames > [--model] [--threshold] [--full] [--format]

Get recommendations for Java code

optional arguments:
  -h, --help            show this help message and exit
  --folder FOLDER       path to Java files
  --filenames [FILENAMES [FILENAMES ...]]
                        list of Java files
  --model MODEL         file where pretrained model is located, the default
                        path is located in site-packages and is installed with
                        aibolit automatically
  --threshold THRESHOLD
                        threshold for predict
  --full                show all recommendations instead of the best one
  --format FORMAT       compact (by default), long or xml. Usage: --format=xml
  --suppress SUPPRESS
  --exclude EXCLUDE [EXCLUDE ...]
```

Would be great to document them.

### PR DESCRIPTION
**Pull request by lyriccoder**
Please specify the following in the description:

1. Fix #608
2. Docs are updated

### CODE REVIEW

**Comment by lyriccoder** [comment]
@yegor256 is it ok now?

**Comment by yegor256** [comment]
@lyriccoder it's better, but the functionality of `--exclude` is still very weird.

**Comment by lyriccoder** [comment]
you have forgotten again, you asked to do it:

https://github.com/cqfn/aibolit/issues/363#issuecomment-646545392

**Comment by yegor256** [comment]
@lyriccoder it seems I made a mistake in the specification. I will make a ticket about it now.

**Comment by acheshkov** [comment]
@rultor merge

**Comment by lyriccoder** [comment]
@acheshkov make an approve, and then merge

**Comment by acheshkov** [comment]
ask @yegor256 to review

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
