### PR TITLE
NCSS filtering

### PR DESCRIPTION
**Pull request by aravij**
Issue #622 

Filtering dataset items based on NCSS. The filtering is done in the following ways. 
 - Calculating NCSS frequencies
 - Calculating diffs of each frequency with next one
 - finding maximum

That way we find the largest fall of frequencies. We can do it several more times for all the larger NCSS.

### CODE REVIEW

**Comment by aravij** [comment]
@acheshkov ok, I'll remove filtering.

**Review by lyriccoder — APPROVED** [review]
ok

**Comment by aravij** [comment]
Class distribution NCSS (till 100, largest NCSS is around 4500 with one extra class with NCSS over 14000).
Quantiles: 75% - 59, 90% - 141, 95% - 243, 99% - 568
class_ncss_distribution

**Comment by aravij** [comment]
Filtering is returned back with 99% quantile.

**Review by lyriccoder — APPROVED** [review]
ok

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
Test

**Pull request merged**
