### PR TITLE
AST API refactoring

### PR DESCRIPTION
**Pull request by aravij**
The PR is big by quantity of file changed. But most of the file are changed slightly and only in import section.
In this PR the following was done:
 - ast relative files moved to a separate package called `ast_framework` (we cant call it just `ast` because of package name collision with one of `numpy` dependency)
- `ASTNodeType` is moved into a separate module

### CODE REVIEW

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by aravij** [comment]
> > @rultor merge
> 
> @acheshkov @aravij Oops, I failed. You can see the full log [here](https://www.rultor.com/t/22507-654273022) (spent 5min)
> 
> ```
> Requirement already satisfied: typing-extensions in /home/r/.local/lib/python3.6/site-packages (from aibolit==0.0.0) (3.7.4.2)
> Requirement already satisfied: soupsieve>=1.2 in /home/r/.local/lib/python3.6/site-packages (from beautifulsoup4==4.8.2->aibolit==0.0.0) (2.0.1)
> Requirement already satisfied: graphviz in /home/r/.local/lib/python3.6/site-packages (from catboost==0.22->aibolit==0.0.0) (0.14)
> Requirement already satisfied: plotly in /home/r/.local/lib/python3.6/site-packages (from catboost==0.22->aibolit==0.0.0) (4.8.2)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from catboost==0.22->aibolit==0.0.0) (1.11.0)
> Requirement already satisfied: requests>=2.7.9 in /home/r/.local/lib/python3.6/site-packages (from codecov==2.0.15->aibolit==0.0.0) (2.24.0)
> Requirement already satisfied: pyflakes<2.2.0,>=2.1.0 in /home/r/.local/lib/python3.6/site-packages (from flake8==3.7.9->aibolit==0.0.0) (2.1.1)
> Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/r/.local/lib/python3.6/site-packages (from flake8==3.7.9->aibolit==0.0.0) (0.6.1)
> Requirement already satisfied: entrypoints<0.4.0,>=0.3.0 in /home/r/.local/lib/python3.6/site-packages (from flake8==3.7.9->aibolit==0.0.0) (0.3)
> Requirement already satisfied: pycodestyle<2.6.0,>=2.5.0 in /home/r/.local/lib/python3.6/site-packages (from flake8==3.7.9->aibolit==0.0.0) (2.5.0)
> Requirement already satisfied: cycler>=0.10 in /home/r/.local/lib/python3.6/site-packages (from matplotlib==3.2.1->aibolit==0.0.0) (0.10.0)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/r/.local/lib/python3.6/site-packages (from matplotlib==3.2.1->aibolit==0.0.0) (2.4.7)
> Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from matplotlib==3.2.1->aibolit==0.0.0) (2.6.1)
> Requirement already satisfied: kiwisolver>=1.0.1 in /home/r/.local/lib/python3.6/site-packages (from matplotlib==3.2.1->aibolit==0.0.0) (1.2.0)
> Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /home/r/.local/lib/python3.6/site-packages (from mypy==0.770->aibolit==0.0.0) (0.4.3)
> Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /home/r/.local/lib/python3.6/site-packages (from mypy==0.770->aibolit==0.0.0) (1.4.1)
> Requirement already satisfied: decorator>=4.3.0 in /home/r/.local/lib/python3.6/site-packages (from networkx==2.4->aibolit==0.0.0) (4.4.2)
> Requirement already satisfied: pytz>=2017.2 in /home/r/.local/lib/python3.6/site-packages (from pandas==1.0.0->aibolit==0.0.0) (2020.1)
> Requirement already satisfied: joblib>=0.11 in /home/r/.local/lib/python3.6/site-packages (from scikit-learn==0.22.1->aibolit==0.0.0) (0.16.0)
> Requirement already satisfied: snowballstemmer>=1.1 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (2.0.0)
> Requirement already satisfied: docutils>=0.12 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (0.16)
> Requirement already satisfied: packaging in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (20.4)
> Requirement already satisfied: sphinxcontrib-devhelp in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.0.2)
> Requirement already satisfied: sphinxcontrib-htmlhelp in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.0.3)
> Requirement already satisfied: sphinxcontrib-jsmath in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.0.1)
> Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from sphinx==2.3.1->aibolit==0.0.0) (39.0.1)
> Requirement already satisfied: alabaster<0.8,>=0.7 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (0.7.12)
> Requirement already satisfied: imagesize in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.2.0)
> Requirement already satisfied: sphinxcontrib-qthelp in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.0.3)
> Requirement already satisfied: Pygments>=2.0 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (2.6.1)
> Requirement already satisfied: Jinja2>=2.3 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (2.11.2)
> Requirement already satisfied: babel!=2.0,>=1.3 in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (2.8.0)
> Requirement already satisfied: sphinxcontrib-serializinghtml in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.1.4)
> Requirement already satisfied: sphinxcontrib-applehelp in /home/r/.local/lib/python3.6/site-packages (from sphinx==2.3.1->aibolit==0.0.0) (1.0.2)
> Requirement already satisfied: retrying>=1.3.3 in /home/r/.local/lib/python3.6/site-packages (from plotly->catboost==0.22->aibolit==0.0.0) (1.3.3)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.7.9->codecov==2.0.15->aibolit==0.0.0) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.7.9->codecov==2.0.15->aibolit==0.0.0) (2.6)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.7.9->codecov==2.0.15->aibolit==0.0.0) (2018.1.18)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.7.9->codecov==2.0.15->aibolit==0.0.0) (1.22)
> Requirement already satisfied: MarkupSafe>=0.23 in /home/r/.local/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx==2.3.1->aibolit==0.0.0) (1.1.1)
> Building wheels for collected packages: aibolit
>   Building wheel for aibolit (setup.py) ... \u001b[?25l-\u0008 \u0008\\u0008 \u0008|\u0008 \u0008/\u0008 \u0008-\u0008 \u0008\\u0008 \u0008|\u0008 \u0008done
> \u001b[?25h  Created wheel for aibolit: filename=aibolit-0.0.0-py2.py3-none-any.whl size=12100688 sha256=10d42147dc62736329667867948a4049df80e75bc930d6cbd7ddce38b19f4c48
>   Stored in directory: /tmp/pip-ephem-wheel-cache-cmgl4i0v/wheels/6a/94/20/fb6515fe78e005049099e68caee81e4e2e53c92744d4ab767f
> Successfully built aibolit
> Installing collected packages: aibolit
> \u001b[33m  WARNING: The script aibolit is installed in '/home/r/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m
> Successfully installed aibolit-0.0.0
> \u001b[33mWARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
> You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m
> python3 -m flake8 aibolit test scripts setup.py --exclude scripts/target/*
> python3 -m mypy aibolit
> aibolit/patterns/non_final_class/non_final_class.py:5: \u001b[1m\u001b[31merror:\u001b(B\u001b[m Skipping analyzing 'aibolit.utils.ast': found module but no type hints or library stubs\u001b(B\u001b[m
> aibolit/patterns/non_final_class/non_final_class.py:5: \u001b[34mnote:\u001b(B\u001b[m See \u001b[4mhttps://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports\u001b(B\u001b[m
> \u001b[1m\u001b[31mFound 1 error in 1 file (checked 137 source files)\u001b(B\u001b[m
> Makefile:36: recipe for target 'typecheck' failed
> make: *** [typecheck] Error 1
> container 97b598f8bb01568b2e65c3ebb6b348b2e52b2dfb9a5140fed247e59e62de5dad is dead
> Mon Jul  6 16:44:39 CEST 2020
> ```

@acheshkov @yegor256  Notice Unicode characters problems in rultor log. Do you know the cause?

**Comment by acheshkov** [comment]
@aravij it complains on typecheck?

**Comment by aravij** [comment]
Yep it is, I will handle this error. But it is just something wrong with server, where rultor is launched. Or may be something wrong with rultor itself. Those `\u0...` means something wrong with Unicode printing.

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
