### PR TITLE
Refactor nested blocks.

### PR DESCRIPTION
**Pull request by aravij**
Delete nested loops and use nested blocks pattern drectly.

### CODE REVIEW

**Comment by aravij** [comment]
There is one test failing. Are we considering a pattern with nested if like this:
```java
if(x == 0) {
    doSmth();
    if(y == 0) {
        doSmth();
    }
    doSmth();
}
```
It does seems to me a direct nesting like in all other test examples with cycles.

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@aravij please take a look

**Comment by aravij** [comment]
@acheshkov The merge will fail anyway, because unit tests are failing. I posted above a comment about current pattern. How does this pattern should behave? I can't extract this information from comments. There is only one such example. is it correct or not?

**Comment by acheshkov** [comment]
> @acheshkov The merge will fail anyway, because unit tests are failing. I posted above a comment about current pattern. How does this pattern should behave? I can't extract this information from comments. There is only one such example. is it correct or not?

@aravij Sorry, did not realize that it's a question.

**Comment by acheshkov** [comment]
> There is one test failing. Are we considering a pattern with nested if like this:
> 
> ```java
> if(x == 0) {
>     doSmth();
>     if(y == 0) {
>         doSmth();
>     }
>     doSmth();
> }
> ```
> 
> It does seems to me a direct nesting like in all other test examples with cycles.

Yes, let's consider this as a pattern match

**Comment by aravij** [comment]
@acheshkov tests are fixed. Please approve and merge.

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
