### PR TITLE
Release 1.2.6

### PR DESCRIPTION
**Pull request by lyriccoder**
fix https://github.com/cqfn/aibolit/issues/524

New release

1) Model was retrained (without LCOM partition)
2) New interface was added for model train and model test
3) Some tests were added model_training with feature selection
4) Fix was added (585)

Now you need to fix __init__.py to fix the number of the future release

### CODE REVIEW

**Comment by lyriccoder** [comment]
@rultor release, tag=`1.2.7rc1`

**Comment by acheshkov** [comment]
@rultor release, tag=`1.2.6rc2`

**Comment by lyriccoder** [comment]
@acheshkov it was released, could you please merge it now?

**Comment by acheshkov** [comment]
@lyriccoder,  merge what?

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
