### PR TITLE
Fix output (Yegor's issue)

### LINKED ISSUE #609: output is too cryptic
This is what I'm getting:

```
$ aibolit check --folder .
Version 1.2.6rc1 is available, but you are using 1.2.5
Show pattern with the largest contribution to Cognitive Complexity
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/VerboseIteratorTest.java score: 0.1
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/VerboseIteratorTest.java[36]: Non final class (P24: 0.10 1/1)
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/VerboseIterableTest.java score: 3.4
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/VerboseIterableTest.java[52]: Var declaration distance for 5 lines (P20_5: 3.40 1/1)
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/StateAwareInputStream.java score: 5.4
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/StateAwareInputStream.java[64]: Array as function argument (P22: 5.40 1/1)
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/StateAwareInputStream.java[69]: Array as function argument (P22: 5.40 1/1)
/Volumes/ssd2/code/takes/src/test/java/org/takes/misc/VerboseListTest.java score: 1.2000000000000002
```

If I'm a new user, I have no idea what this means. I need more details.

I'm suggesting: 

  - remove the lines announcing the score, they are pointless
  - print a link at the end of the output, where I can find the description of each `Pxx` pattern

### PR DESCRIPTION
**Pull request by lyriccoder**
Please specify the following in the description:

1. Fix #609 
2. Fixes output

### CODE REVIEW

**Comment by lyriccoder** [comment]
@yegor256 , fixed. Do u like it now?

```Show pattern with the largest contribution to Cognitive Complexity
D:\target\0001\fast\Configuration.java[1280]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[1690]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[1692]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[1842]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[1852]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2050]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2054]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2090]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2100]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2272]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2322]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2601]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2612]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2693]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2822]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\Configuration.java[2846]: Count If Return (P6: 3.20 1/1)
D:\target\0001\fast\JndiRmiClientInterceptor.java[271]: Multiple try (P11: 7.40 1/1)
D:\target\0001\fast\JndiRmiClientInterceptor.java[365]: Multiple try (P11: 7.40 1/1)
D:\target\0001\fast\LottieImageAsset.java[10]: Non final class (P24: 1.70 1/1)
Total score: 4.10, files seen: 3, ncss 581
You can find all information about patterns here: https://github.com/cqfn/aibolit/blob/master/PATTERNS.md```

**Comment by yegor256** [comment]
@lyriccoder yes, looks good now

**Comment by lyriccoder** [comment]
@acheshkov @aravij could you please accept review before merging?

**Comment by acheshkov** [comment]
@rultor merge

**Pull request merged**
